[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# Handle API requests
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
  headers = { X-From = "Netlify" }

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  exclude = ["/api/*", "/.netlify/*", "/assets/*"]

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "express-session", "@neondatabase/serverless", "drizzle-orm", "zod", "pg", "connect-pg-simple"]
  included_files = ["node_modules/**/*"]

[functions.api]
  format = "esm"
  external_node_modules = [
    "express",
    "express-session",
    "@neondatabase/serverless",
    "drizzle-orm",
    "zod",
    "pg",
    "connect-pg-simple",
    "serverless-http"
  ] 