[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# Important: Configure these environment variables in the Netlify UI
# DATABASE_URL - Your Neon database connection string
# JWT_SECRET - Secret key for JWT token generation/verification

# Handle API requests
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
  headers = { X-From = "Netlify" }

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  exclude = ["/api/*", "/.netlify/*", "/assets/*"]

[functions]
  node_bundler = "esbuild"
  external_node_modules = [
    "express",
    "express-session",
    "@neondatabase/serverless",
    "drizzle-orm",
    "zod",
    "pg",
    "connect-pg-simple"
  ]
  included_files = [
    "server/**/*",
    "shared/**/*"
  ]

# API function configuration - increased timeout for Neon cold starts
[functions.api]
  format = "esm"
  timeout = 30
  memory = 1024
  external_node_modules = [
    "express",
    "express-session",
    "@neondatabase/serverless",
    "drizzle-orm",
    "zod",
    "pg",
    "connect-pg-simple",
    "serverless-http"
  ] 